### ISSUE TITLE
Update seat prices for 2020

### ISSUE THREAD

**Issue by yaakovgrossman** [judaschwartz/levavrohom#5]
https://github.com/judaschwartz/levavrohom/blob/638cd72b1a8463b39b04b4b0a4d0e3e3d82e89c0/reserve-a-seat.html#L129

Please update seat prices (and paypal links) as follows:

NON MEMBERS: $120 RH & YK;    $90 RH;     $45 YK

MEMBERS:          $54 RH & YK;     $45 RH;     $30 YK 

Thanks!

**Comment by judaschwartz** [comment]
Done
________________________________
